name: Publish Cloudformation templates

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write # required for requesting the JWT
  contents: read # required for actions/checkout

jobs:
  call-tests:
    uses: ./.github/workflows/test.yml
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"
      - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::119672615070:role/StackSet-CustomControlTower--CfnAssetsPublisherRole-fo8sJRyzir1L
          role-session-name: rvm-github-publishing
          aws-region: eu-west-2
      - run: |
          ASSETS_BUCKET=stackset-customcontroltower-cfn-asset-assetsbucket-istfefgfkzgy make publish
      - uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: |
            packaged.yaml
